name: Backend live Monitoring

on:
  schedule:
    - cron: "0 * * * *" 
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping App
        run: |
          echo "Pinging ${{ secrets.BASE_URL }}/health ..."

          RESPONSE=$(curl -s -o response.txt -w "STATUS:%{http_code} TIME:%{time_total}s SIZE:%{size_download}B\n" "${{ secrets.BASE_URL }}/health")

          echo "------ Backend Health Check ------"
          echo "Body: $(cat response.txt)"
          echo "Meta: $RESPONSE"
          echo "--------------------------------"
          
          if [[ $RESPONSE != *"STATUS:200"* ]]; then
            echo "App is DOWN or unhealthy!"
            exit 1
          else
            echo "App is UP and healthy."
          fi
